name: Draft an Auto-Release on Version Bump

on:
  push:
    branches:
      - test-auto-release

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create tags

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to ensure we can check if tag exists

      # Read the VERSION file content
      - name: Read VERSION file
        id: version
        run: echo "version=$(cat VERSION | tr -d '[:space:]')" >> $GITHUB_OUTPUT